# 2-2 파이썬 프로그래밍 기초_Pandas
### series

In [1]:
import pandas as pd

##### list 사용하여 생성

In [6]:
#인덱스값 설정하여 Series 생성
data = pd.Series([10,20,30,40,50], index=['a','b','c','d','e'])
print(data,"\n")
print("인덱스 : ", data.index)
print("값 : ", data.values)

a    10
b    20
c    30
d    40
e    50
dtype: int64 

인덱스 :  Index(['a', 'b', 'c', 'd', 'e'], dtype='object')
값 :  [10 20 30 40 50]


In [3]:
#인덱스로 값을 얻음
print("index가 b인 값은 : ",data['b'])

index가 b인 값은 :  20


##### dict를 사용하여 생성

In [7]:
data = pd.Series({
    'a' : 10,
    'b' : 20,
    'c' : 30,
    'd' : 40,
    'e' : 50
})
print(data,"\n")
print("인덱스 : ", data.index)
print("값 : ", data.values)

a    10
b    20
c    30
d    40
e    50
dtype: int64 

인덱스 :  Index(['a', 'b', 'c', 'd', 'e'], dtype='object')
값 :  [10 20 30 40 50]


In [8]:
print("index가 b인 값은 : ",data['b'])

index가 b인 값은 :  20


### DataFrame
##### numpy배열을 사용하여 DataFrame생성

In [11]:
data = pd.DataFrame([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
data

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [16]:
print(data.values)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


##### dict를 통해 DataFrame 생성

In [19]:
data = pd.DataFrame({
    'student' : ['bob','sally','marco','robin'],
    'dept' : ['computer','software','software','media'],
    'grade' : [2,3,4,1]
})
data

student      dept  grade
0     bob  computer      2
1   sally  software      3
2   marco  software      4
3   robin     media      1

##### Column을 얻는 방법 2가지

In [21]:
print(data['student'])
print(data.student)

0      bob
1    sally
2    marco
3    robin
Name: student, dtype: object


0      bob
1    sally
2    marco
3    robin
Name: student, dtype: object

##### Row를 얻는 방법

In [33]:
data = {
    'student' : ['bob','sally','marco','robin'],
    'dept' : ['computer','software','software','media'],
    'grade' : [2,3,4,1]
}
df = pd.DataFrame(data, index = [10,20,30,40])
df

student      dept  grade
10     bob  computer      2
20   sally  software      3
30   marco  software      4
40   robin     media      1

In [34]:
# iloc 사용하는 방법
df.iloc[:2]

student      dept  grade
10     bob  computer      2
20   sally  software      3

In [35]:
# loc 사용하는 방법
df.loc[:30]

student      dept  grade
10     bob  computer      2
20   sally  software      3
30   marco  software      4

##### DataFrame의 여러가지 메서드 알아보기

In [36]:
# 데이터 값으로 정렬하기
df.sort_values(by='grade')

student      dept  grade
40   robin     media      1
10     bob  computer      2
20   sally  software      3
30   marco  software      4

In [37]:
# Row 삭제
df.drop(10)    # index가 10인 row 삭제

student      dept  grade
20   sally  software      3
30   marco  software      4
40   robin     media      1

In [38]:
# Column 삭제
df.drop('dept',axis=1)    # column명이 'dept'인 column 삭제

student  grade
10     bob      2
20   sally      3
30   marco      4
40   robin      1

In [39]:
# 중복행 제거
df.drop_duplicates('dept')

student      dept  grade
10     bob  computer      2
20   sally  software      3
40   robin     media      1

In [40]:
# 값 치환하기
df.replace({'grade':4},{'grade':3})

student      dept  grade
10     bob  computer      2
20   sally  software      3
30   marco  software      3
40   robin     media      1

In [41]:
# 결측치
df.reindex([10,20,30,40,50])

student      dept  grade
10     bob  computer    2.0
20   sally  software    3.0
30   marco  software    4.0
40   robin     media    1.0
50     NaN       NaN    NaN

In [42]:
# 조건부 인덱싱
df[(df['dept'].str.len()==8)&(df['grade']==3)]

student      dept  grade
20   sally  software      3