# 2-2 파이썬 프로그래밍 기초_Numpy
### 배열 생성

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [3]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
c = np.array([1.1,2.4,3.6])
c

array([1.1, 2.4, 3.6])

In [7]:
type(c)    # numpy.ndarray

numpy.ndarray

In [21]:
print(np.ndim(b))
print(np.shape(b))

2
(3, 3)


##### 추가적인 배열 생성 방법

In [23]:
# 모든 값이 0인 4x4배열 생성
d = np.zeros((4,4))
d

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
# 2x2 단위행렬 생성
e = np.eye(2)
e

array([[1., 0.],
       [0., 1.]])

### 배열 인덱싱

In [28]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
b = a[:2,:2]
b

array([[1, 2],
       [4, 5]])

In [35]:
print(a[1,1])    # 5출력
b[1,1] = 3
print(a[1,1])    # 3출력

5
3


### 자료형

In [41]:
x = np.array([1.1,1.2])
print(x.dtype)    # float64 출력

float64


In [42]:
y = np.array([1,1],dtype=np.int64)
print(y.dtype)    # int64 출력

int64


### 배열 연산

In [49]:
x = np.array([[1,2],[4,8]], dtype=np.float64)
y = np.array([[1,4],[9,16]], dtype=np.float64)

In [54]:
print(np.add(x,y))
print(x+y)

[[ 2.  6.]
 [13. 24.]]
[[ 2.  6.]
 [13. 24.]]


In [55]:
print(np.subtract(y,x))
print(y-x)

[[0. 2.]
 [5. 8.]]
[[0. 2.]
 [5. 8.]]


In [57]:
print(np.multiply(x,y))
print(x*y)

[[  1.   8.]
 [ 36. 128.]]
[[  1.   8.]
 [ 36. 128.]]
[[1.         0.5       ]
 [0.44444444 0.5       ]]
[[1. 2.]
 [3. 4.]]


In [58]:
print(np.divide(x,y))
print(x/y)

[[1.         0.5       ]
 [0.44444444 0.5       ]]
[[1.         0.5       ]
 [0.44444444 0.5       ]]


In [59]:
print(np.sqrt(y))

[[1. 2.]
 [3. 4.]]


In [66]:
x = np.array([[1,2],[3,4]])
print(np.sum(x))    # 10 출력
print(np.sum(x,axis=0))    # [4 6] 출력
print(np.sum(x,axis=1))    # [3 7] 출력

10
[4 6]
[3 7]


In [67]:
print(x.T)

[[1 3]
 [2 4]]
